# Generated by Django 4.0.4 on 2022-11-26 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('cirugiaId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Cirugía')),
                ('cirugiaNombre', models.CharField(max_length=100, verbose_name='Nombre Cirugia')),
            ],
        ),
        migrations.CreateModel(
            name='InfIntervencion',
            fields=[
                ('interId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Intervención')),
                ('interFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Intervención')),
                ('interHora', models.DateField(default=django.utils.timezone.now, verbose_name='Hora Intervención')),
                ('interNombre', models.CharField(max_length=50, verbose_name='Nombre Intervención')),
                ('interAnestesia', models.CharField(max_length=50, verbose_name='Anestesia Intervención')),
                ('interApoyo', models.CharField(max_length=50, null=True, verbose_name='Apoyo Intervención')),
                ('interCantApoyo', models.IntegerField(null=True, verbose_name='Cantidad de Apoyo Intervención')),
                ('interDesc', models.CharField(max_length=50, null=True, verbose_name='Descripción Intervención')),
            ],
        ),
        migrations.CreateModel(
            name='InfTraslado',
            fields=[
                ('trasId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Traslado')),
                ('trasFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Traslado')),
                ('trasHora', models.DateField(default=django.utils.timezone.now, verbose_name='Hora Traslado')),
                ('trasEquipo', models.CharField(max_length=50, verbose_name='Equipo Traslado')),
                ('trasSala', models.CharField(max_length=50, verbose_name='Sala Traslado')),
                ('trasDesc', models.CharField(max_length=50, null=True, verbose_name='Descripción Traslado')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paRut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Paciente')),
                ('paNombres', models.CharField(max_length=100, verbose_name='Nombres Paciente')),
                ('paApellidos', models.CharField(max_length=100, verbose_name='Apellidos Paciente')),
                ('paCorreoEmerg', models.CharField(max_length=50, verbose_name='Correo Emergencia Paciente')),
                ('paCirugia', models.CharField(max_length=150, verbose_name='Dirección Paciente')),
                ('paAlergias', models.CharField(max_length=50, null=True, verbose_name='Alergias Paciente')),
                ('paCirugiasAnteriores', models.CharField(max_length=50, null=True, verbose_name='Cirugia Anteriores Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userRut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Usuario')),
                ('userNombres', models.CharField(max_length=100, verbose_name='Nombres Usuario')),
                ('userApellidos', models.CharField(max_length=100, verbose_name='Apellidos Usuario')),
                ('userCorreo', models.CharField(max_length=50, verbose_name='Correo Usuario')),
                ('userPassword', models.CharField(max_length=50, verbose_name='Contraseña Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegRecepcion',
            fields=[
                ('regRecepId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Registro de Recepción')),
                ('regRecepFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Recepción')),
                ('regRecepHora', models.DateField(default=django.utils.timezone.now, verbose_name='Hora Registro de Recepción')),
                ('regRecepPac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RegQuirurgico',
            fields=[
                ('regQuiId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Registro de Quirúrgico')),
                ('regQuiFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Quirúrgico')),
                ('regQuiHora', models.DateField(default=django.utils.timezone.now, verbose_name='Hora Registro de Quirúrgico')),
                ('regQuiInter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.infintervencion')),
                ('regQuiPac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('regQuiRec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.regrecepcion')),
                ('regQuiTras', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.inftraslado')),
            ],
        ),
    ]
