# Generated by Django 4.0.4 on 2022-11-28 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('cirugiaId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Cirugía')),
                ('cirugiaNombre', models.CharField(max_length=100, verbose_name='Nombre Cirugia')),
            ],
            options={
                'ordering': ['cirugiaNombre'],
            },
        ),
        migrations.CreateModel(
            name='InfIntervencion',
            fields=[
                ('interId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Intervención')),
                ('interFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Intervención')),
                ('interAnestesia', models.CharField(max_length=50, verbose_name='Anestesia Intervención')),
                ('interApoyo', models.CharField(blank=True, default='', max_length=50, verbose_name='Apoyo Intervención')),
                ('interCantApoyo', models.IntegerField(blank=True, default=0, verbose_name='Cantidad de Apoyo Intervención')),
                ('interObs', models.CharField(blank=True, default='', max_length=250, verbose_name='Observación Intervención')),
                ('interInsumos', models.CharField(blank=True, default=0, max_length=500, verbose_name='Recuento de Insumos Intervención')),
                ('interNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cirugia')),
            ],
        ),
        migrations.CreateModel(
            name='InfTraslado',
            fields=[
                ('trasId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Traslado')),
                ('trasFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Traslado')),
                ('trasEquipo', models.CharField(max_length=50, verbose_name='Equipo Traslado')),
                ('trasSala', models.CharField(max_length=50, verbose_name='Sala Traslado')),
                ('trasObs', models.CharField(blank=True, default='', max_length=250, verbose_name='Observación Traslado')),
                ('trasInter', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.infintervencion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paRut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Paciente')),
                ('paNombres', models.CharField(max_length=100, verbose_name='Nombres Paciente')),
                ('paApellidos', models.CharField(max_length=100, verbose_name='Apellidos Paciente')),
                ('paCorreoEmerg', models.CharField(max_length=50, verbose_name='Correo Emergencia Paciente')),
                ('paAlergias', models.CharField(blank=True, default='', max_length=100, verbose_name='Alergias Paciente')),
                ('paCirugiasAnteriores', models.CharField(blank=True, default='', max_length=250, verbose_name='Cirugia Anteriores Paciente')),
                ('paCirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cirugia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userRut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Usuario')),
                ('userNombres', models.CharField(max_length=100, verbose_name='Nombres Usuario')),
                ('userApellidos', models.CharField(max_length=100, verbose_name='Apellidos Usuario')),
                ('userCorreo', models.CharField(max_length=50, verbose_name='Correo Usuario')),
                ('userPassword', models.CharField(max_length=50, verbose_name='Contraseña Usuario')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegRecepcion',
            fields=[
                ('regRecepId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Registro de Recepción')),
                ('regRecepFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Recepción')),
                ('regRecepPac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RegQuirurgico',
            fields=[
                ('regQuiId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id  Registro de Quirúrgico')),
                ('regQuiFecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Quirúrgico')),
                ('regQuiInter', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.infintervencion')),
                ('regQuiRec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.regrecepcion')),
                ('regQuiTras', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.inftraslado')),
            ],
        ),
        migrations.AddField(
            model_name='inftraslado',
            name='trasRecep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.regrecepcion'),
        ),
        migrations.AddField(
            model_name='infintervencion',
            name='interRecep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.regrecepcion'),
        ),
    ]
