# Generated by Django 4.0.4 on 2022-11-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_inftraslado_trasinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inftraslado',
            name='trasInter',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.infintervencion'),
        ),
    ]
