# Generated by Django 4.0.4 on 2022-11-28 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inftraslado_trasinter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regquirurgico',
            name='regQuiFecha',
            field=models.DateField(default=datetime.datetime, verbose_name='Fecha Registro de Quirúrgico'),
        ),
    ]
