# Generated by Django 4.0.4 on 2022-11-28 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_regquirurgico_regquifecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regquirurgico',
            name='regQuiFecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Quirúrgico'),
        ),
    ]
