# Generated by Django 4.0.4 on 2022-11-26 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_infintervencion_interfecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infintervencion',
            name='interHora',
        ),
        migrations.RemoveField(
            model_name='inftraslado',
            name='trasHora',
        ),
        migrations.RemoveField(
            model_name='regquirurgico',
            name='regQuiHora',
        ),
        migrations.RemoveField(
            model_name='regrecepcion',
            name='regRecepHora',
        ),
        migrations.AlterField(
            model_name='infintervencion',
            name='interFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 34, 24, 600734), verbose_name='Fecha Intervención'),
        ),
        migrations.AlterField(
            model_name='inftraslado',
            name='trasFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 34, 24, 601730), verbose_name='Fecha Traslado'),
        ),
        migrations.AlterField(
            model_name='regquirurgico',
            name='regQuiFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 34, 24, 601730), verbose_name='Fecha Registro de Quirúrgico'),
        ),
        migrations.AlterField(
            model_name='regrecepcion',
            name='regRecepFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 34, 24, 600734), verbose_name='Fecha Registro de Recepción'),
        ),
    ]
