# Generated by Django 4.0.4 on 2022-11-26 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_infintervencion_interhora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infintervencion',
            name='interDesc',
        ),
        migrations.RemoveField(
            model_name='inftraslado',
            name='trasDesc',
        ),
        migrations.AddField(
            model_name='infintervencion',
            name='interObs',
            field=models.CharField(max_length=250, null=True, verbose_name='Observación Intervención'),
        ),
        migrations.AddField(
            model_name='inftraslado',
            name='trasObs',
            field=models.CharField(max_length=250, null=True, verbose_name='Observación Traslado'),
        ),
        migrations.AlterField(
            model_name='infintervencion',
            name='interFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 38, 27, 671892), verbose_name='Fecha Intervención'),
        ),
        migrations.AlterField(
            model_name='inftraslado',
            name='trasFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 38, 27, 672889), verbose_name='Fecha Traslado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paAlergias',
            field=models.CharField(max_length=100, null=True, verbose_name='Alergias Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paCirugiasAnteriores',
            field=models.CharField(max_length=250, null=True, verbose_name='Cirugia Anteriores Paciente'),
        ),
        migrations.AlterField(
            model_name='regquirurgico',
            name='regQuiFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 38, 27, 672889), verbose_name='Fecha Registro de Quirúrgico'),
        ),
        migrations.AlterField(
            model_name='regrecepcion',
            name='regRecepFecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 18, 38, 27, 671892), verbose_name='Fecha Registro de Recepción'),
        ),
    ]
