# Generated by Django 4.0.4 on 2022-11-28 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_regquirurgico_regquifecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infintervencion',
            name='interFecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Intervención'),
        ),
        migrations.AlterField(
            model_name='inftraslado',
            name='trasFecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Traslado'),
        ),
        migrations.AlterField(
            model_name='regrecepcion',
            name='regRecepFecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Recepción'),
        ),
    ]
