# Generated by Django 4.0.4 on 2022-11-26 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_infintervencion_interdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infintervencion',
            name='interApoyo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Apoyo Intervención'),
        ),
        migrations.AlterField(
            model_name='infintervencion',
            name='interCantApoyo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad de Apoyo Intervención'),
        ),
        migrations.AlterField(
            model_name='infintervencion',
            name='interFecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Intervención'),
        ),
        migrations.AlterField(
            model_name='infintervencion',
            name='interObs',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Observación Intervención'),
        ),
        migrations.AlterField(
            model_name='inftraslado',
            name='trasFecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Traslado'),
        ),
        migrations.AlterField(
            model_name='inftraslado',
            name='trasObs',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Observación Traslado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paAlergias',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Alergias Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paCirugiasAnteriores',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Cirugia Anteriores Paciente'),
        ),
        migrations.AlterField(
            model_name='regquirurgico',
            name='regQuiFecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Quirúrgico'),
        ),
        migrations.AlterField(
            model_name='regrecepcion',
            name='regRecepFecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro de Recepción'),
        ),
    ]
