# Generated by Django 4.0.4 on 2022-11-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_infintervencion_interapoyo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infintervencion',
            name='interInsumos',
            field=models.IntegerField(blank=True, default=0, verbose_name='Recuento de Insumos Intervención'),
        ),
    ]
