# Generated by Django 4.0.4 on 2022-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_infintervencion_interinsumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infintervencion',
            name='interInsumos',
            field=models.IntegerField(blank=True, default=0, verbose_name='Recuento de Insumos Intervención'),
        ),
    ]
